# Machine Learning Zoomcamp

## 1.9 Introduction to Pandas

Plan:

* Data Frames
* Series
* Index
* Accessing elements
* Element-wise operations
* Filtering
* String operations
* Summarizing operations
* Missing values
* Grouping
* Getting the NumPy arrays

In [1]:
# 수치 연산·배열 처리를 돕는 넘파이(NumPy)를 np 별칭으로 불러옵니다.
import numpy as np
# 표 형태 데이터 조작·분석용 판다스(Pandas)를 pd 별칭으로 불러옵니다.
import pandas as pd

## DataFrames

In [2]:
# 자동차 제원 정보를 2차원 리스트로 정의합니다. 각 안쪽 리스트 = 한 대의 차량(한 행).
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],  # 1991년식 닛산 스탠자
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],  # 2017 소나타 (Engine HP 누락 → None)
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],  # 2010 로터스 엘리스
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],  # 2017 GMC 아카디아
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],  # 2017 닛산 프론티어
]

# 각 열(Column)에 붙일 이름을 순서대로 적은 문자열 리스트입니다.
columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [3]:
# 2차원 데이터와 컬럼 이름을 합쳐 판다스 데이터프레임(df)을 만듭니다.
df = pd.DataFrame(data, columns=columns)

In [4]:
# 데이터프레임을 그대로 출력하면 표 형태로 정렬되어 보입니다.
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [5]:
# 각 행을 '열 이름(키): 값' 딕셔너리로 두고, 그 딕셔너리들을 리스트로 묶은 형태입니다.
data = [
    {
        "Make": "Nissan",  # 제조사
        "Model": "Stanza",  # 모델명
        "Year": 1991,  # 연식
        "Engine HP": 138.0,  # 엔진 마력
        "Engine Cylinders": 4,  # 실린더 개수
        "Transmission Type": "MANUAL",  # 변속기
        "Vehicle_Style": "sedan",  # 차체 스타일
        "MSRP": 2000  # 권장소비자가격
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,  # 누락 값은 파이썬 None 으로 표시
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [6]:
# 딕셔너리 리스트로 데이터프레임을 만듭니다. 딕셔너리 키가 컬럼명이 됩니다.
df = pd.DataFrame(data)
# 생성된 데이터프레임을 출력합니다.
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [7]:
# 위에서부터 n개 행만 미리 봅니다. (여기선 2행)
df.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

## Series

In [8]:
# 점(.) 표기법은 열 이름에 공백이 있으면 문법 오류가 납니다. (의도된 실패 예시)
df.Engine HP

SyntaxError: invalid syntax (3444319199.py, line 2)

In [ ]:
# 대괄호로 열 이름을 지정하면 공백이 있어도 됩니다. 결과는 1차원 시리즈(Series)입니다.
df['Engine HP']

In [ ]:
# 여러 열을 한꺼번에 고르려면 리스트를 한 번 더 감쌉니다. 결과는 데이터프레임입니다.
df[['Make', 'Model', 'MSRP']]

In [ ]:
# 'id'라는 새 열을 추가하고 1~5 값을 넣습니다.
df['id'] = [1, 2, 3, 4, 5]

In [ ]:
# 이미 있는 'id' 열 값을 새 리스트로 덮어씁니다.
df['id'] = [10, 20, 30, 40, 50]

In [9]:
# 'id' 열이 반영된 현재 데이터프레임을 확인합니다.
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [10]:
# del 로 더 이상 필요 없는 'id' 열을 삭제합니다.
del df['id']

KeyError: 'id'

In [ ]:
# 'id' 열이 삭제된 데이터프레임을 확인합니다.
df

## Index

In [ ]:
# 행을 구분하는 인덱스(기본: 0부터 시작하는 정수)를 조회합니다.
df.index

In [ ]:
# 'Make' 시리즈가 가진 인덱스도 조회합니다. (보통 데이터프레임 인덱스와 같습니다)
df.Make.index

In [ ]:
# 행 인덱스 라벨을 알파벳 'a'~'e'로 직접 지정합니다.
df.index = ['a', 'b', 'c', 'd', 'e']

In [ ]:
# 인덱스가 알파벳으로 바뀐 데이터프레임을 확인합니다.
df

In [11]:
# iloc: 라벨 이름과 무관하게, 위치 기준(0부터)으로 1·2·4번째 행을 고릅니다.
df.iloc[[1, 2, 4]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [12]:
# 문자열 인덱스를 버리고(drop=True) 0부터 시작하는 기본 정수 인덱스로 되돌립니다.
df = df.reset_index(drop=True)

In [13]:
# 인덱스가 기본 정수로 초기화된 데이터프레임을 확인합니다.
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

## Accessing elements

## Element-wise operations

In [14]:
# 'Engine HP' 열의 모든 값에 각각 2를 곱합니다. (요소별 연산, for문 불필요)
df['Engine HP'] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

In [15]:
# 각 행의 Year가 2015 이상인지 True/False 시리즈로 반환합니다.
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

## Filtering

In [16]:
# Make가 'Nissan'인 행만 남깁니다. (불리언 조건으로 필터링)
df[
    df['Make'] == 'Nissan'
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [17]:
# 조건을 소괄호로 감싼 뒤 & (그리고)로 연결합니다. | 는 또는입니다.
df[
    (df['Make'] == 'Nissan') & (df['Year'] >= 2015)
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

## String operations

In [18]:
# 파이썬 기본 문자열 replace 예시: 공백을 언더스코어(_)로 바꿉니다.
'machine learning zoomcamp'.replace(' ', '_')

'machine_learning_zoomcamp'

In [19]:
# .str 접근자로 열 전체 텍스트를 소문자로 바꿉니다.
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [20]:
# 공백→언더스코어 치환 후 소문자 변환을 이어서(chaining) 적용하고, 원래 열에 저장합니다.
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ', '_').str.lower()

In [21]:
# 문자열 정리가 반영된 데이터프레임을 확인합니다.
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

## Summarizing operations

In [23]:
# 수치형 열의 개수·평균·표준편차·최소·사분위·최댓값을 요약하고, 소수 둘째 자리로 반올림합니다.
df.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [22]:
df.describe()

              Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [24]:
# 열마다 중복을 제외한 고유값(unique) 개수를 셉니다.
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

## Missing values

In [25]:
# 결측값(Null/NaN)이면 True. 열별로 True 개수를 합쳐 결측 개수를 봅니다.
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

## Grouping

`
# (참고) SQL로 쓰면 아래와 비슷한 의미입니다. 실행용 파이썬 코드가 아닙니다.
SELECT 
    transmission_type,
    AVG(MSRP)
FROM
    cars
GROUP BY
    transmission_type
`

In [26]:
# Transmission Type별로 묶은 뒤, 각 그룹의 MSRP 최댓값을 구합니다.
df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

## Getting the NumPy arrays

In [27]:
# 시리즈에서 값만 꺼내 순수 넘파이 배열(array)로 얻습니다. (ML 입력 등에 자주 사용)
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [29]:
# 각 행을 하나의 딕셔너리로 만든 리스트로 변환합니다. (orient='records')
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]

In [28]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340